using Microsoft.AspNetCore.Mvc;
using DotNetSample.Core;
using System;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace DotNetSample.Api.Controllers
{
    /// <summary>
    /// Controller that manages customers.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public class CustomersController : ControllerBase
    {
        /// <summary>
        /// Repository for customer persistence operations.
        /// </summary>
        private readonly IRepository<Customer> _repo;

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomersController"/> class.
        /// </summary>
        /// <param name="repo">Repository used to access customer data.</param>
        public CustomersController(IRepository<Customer> repo)
        {
            _repo = repo;
        }

        /// <summary>
        /// Returns all customers.
        /// </summary>
        /// <returns>A collection of <see cref="Customer"/>.</returns>
        [HttpGet]
        public async Task<IEnumerable<Customer>> Get() => await _repo.ListAsync();

        /// <summary>
        /// Returns a page of customers.
        /// </summary>
        /// <param name="pageNumber">1-based page number.</param>
        /// <param name="pageSize">Number of items per page.</param>
        /// <returns>Paged list of customers.</returns>
        [HttpGet("paged")]
        public async Task<ActionResult<IEnumerable<Customer>>> GetPaged(int pageNumber = 1, int pageSize = 10)
        {
            var customers = await _repo.ListAsync();
            var pagedCustomers = customers
                .Skip((pageNumber - 1) * pageSize)
                .Take(pageSize)
                .ToList();
            return Ok(pagedCustomers);
        }   
        

        /// <summary>
        /// Gets a single customer by id.
        /// </summary>
        /// <param name="id">Customer identifier.</param>
        /// <returns>The customer if found; otherwise 404.</returns>
        [HttpGet("{id}")]
        public async Task<ActionResult<Customer>> Get(Guid id)
        {
            var c = await _repo.GetAsync(id);
            if (c == null) return NotFound();
            return c;
        }

        /// <summary>
        /// Creates a new customer.
        /// </summary>
        /// <param name="customer">Customer to create. The Id will be generated by the server.</param>
        /// <returns>201 Created with the created customer.</returns>
        [HttpPost]
        public async Task<ActionResult> Post(Customer customer)
        {
            customer.Id = Guid.NewGuid();
            await _repo.AddAsync(customer);
            return CreatedAtAction(nameof(Get), new { id = customer.Id }, customer);
        }

        /// <summary>
        /// Updates an existing customer.
        /// </summary>
        /// <param name="id">Identifier of the customer to update.</param>
        /// <param name="customer">Updated customer values.</param>
        /// <returns>204 NoContent on success or 404 if not found.</returns>
        [HttpPut("{id}")]
        public async Task<ActionResult> Put(Guid id, Customer customer)
        {
            var existing = await _repo.GetAsync(id);
            if (existing == null) return NotFound();
            existing.Name = customer.Name;
            existing.Email = customer.Email;
            await _repo.UpdateAsync(existing);
            return NoContent();
        }

        /// <summary>
        /// Deletes a customer by id.
        /// </summary>
        /// <param name="id">Identifier of the customer to delete.</param>
        /// <returns>204 NoContent.</returns>
        [HttpDelete("{id}")]
        public async Task<ActionResult> Delete(Guid id)
        {
            await _repo.DeleteAsync(id);
            return NoContent();
        }
    }
}
