using Microsoft.AspNetCore.Mvc;
using DotNetSample.Core;
using System;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace DotNetSample.Api.Controllers
{
    /// <summary>
    /// Controller that manages products.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public class ProductsController : ControllerBase
    {
        /// <summary>
        /// Repository for product persistence operations.
        /// </summary>
        private readonly IRepository<Product> _repo;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductsController"/> class.
        /// </summary>
        /// <param name="repo">Repository used to access product data.</param>
        public ProductsController(IRepository<Product> repo)
        {
            _repo = repo;
        }

        /// <summary>
        /// Returns all products.
        /// </summary>
        /// <returns>A collection of <see cref="Product"/>.</returns>
        [HttpGet]
        public async Task<IEnumerable<Product>> Get() => await _repo.ListAsync();

        /// <summary>
        /// Gets a single product by id.
        /// </summary>
        /// <param name="id">Product identifier.</param>
        /// <returns>The product if found; otherwise 404.</returns>
        [HttpGet("{id}")]
        public async Task<ActionResult<Product>> Get(Guid id)
        {
            var p = await _repo.GetAsync(id);
            if (p == null) return NotFound();
            return p;
        }

        /// <summary>
        /// Creates a new product.
        /// </summary>
        /// <param name="product">Product to create. The Id will be generated by the server.</param>
        /// <returns>201 Created with the created product.</returns>
        [HttpPost]
        public async Task<ActionResult> Post(Product product)
        {
            product.Id = Guid.NewGuid();
            await _repo.AddAsync(product);
            return CreatedAtAction(nameof(Get), new { id = product.Id }, product);
        }

        /// <summary>
        /// Updates an existing product.
        /// </summary>
        /// <param name="id">Identifier of the product to update.</param>
        /// <param name="product">Updated product values.</param>
        /// <returns>204 NoContent on success or 404 if not found.</returns>
        [HttpPut("{id}")]
        public async Task<ActionResult> Put(Guid id, Product product)
        {
            var existing = await _repo.GetAsync(id);
            if (existing == null) return NotFound();
            existing.Name = product.Name;
            existing.Price = product.Price;
            existing.Stock = product.Stock;
            await _repo.UpdateAsync(existing);
            return NoContent();
        }

        /// <summary>
        /// Deletes a product by id.
        /// </summary>
        /// <param name="id">Identifier of the product to delete.</param>
        /// <returns>204 NoContent.</returns>
        [HttpDelete("{id}")]
        public async Task<ActionResult> Delete(Guid id)
        {
            await _repo.DeleteAsync(id);
            return NoContent();
        }
    }
}
